apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic
spec:
  replicas: 10
  selector:
    matchLabels:
      app: linux
  template:
    metadata:
      labels:
        app: linux
    spec:
      containers:
      - command: null
        image: null
        name: null
      nodeSelector:
        ostype: linux
